name: py3tensorflow
channels:
  - defaults
dependencies:
  - _nb_ext_conf=0.4.0=py36_1
  - alabaster=0.7.10=py36hcd07829_0
  - anaconda-client=1.6.14=py36_0
  - asn1crypto=0.24.0=py36_0
  - babel=2.5.3=py36_0
  - backcall=0.1.0=py36_0
  - bleach=2.1.3=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.5=py36h945400d_0
  - chardet=3.0.4=py36h420ce6e_1
  - clyent=1.2.2=py36hb10d595_1
  - colorama=0.3.9=py36h029ae33_0
  - cryptography=2.2.2=py36hfa6e2cd_0
  - cycler=0.10.0=py36h009560c_0
  - decorator=4.2.1=py36_0
  - docutils=0.14=py36h6012d8f_0
  - entrypoints=0.2.3=py36hfd66bb0_2
  - expat=2.2.5=hcc4222d_0
  - freetype=2.8=h51f8f2c_1
  - future=0.16.0=py36_1
  - html5lib=1.0.1=py36h047fa9f_0
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - idna=2.6=py36h148d497_1
  - imagesize=1.0.0=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.0=py36_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.2.0=py36_0
  - jedi=0.11.1=py36_1
  - jinja2=2.10=py36h292fed1_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py36h56e9d50_0
  - kiwisolver=1.0.1=py36h12c3424_0
  - libiconv=1.15=h1df5818_7
  - libpng=1.6.34=h79bbb47_0
  - libtiff=4.0.9=h0f13578_0
  - libxml2=2.9.8=hc33b523_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.0=py36h0e26971_1
  - matplotlib=2.2.2=py36h153e9ff_1
  - mistune=0.8.3=py36_0
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h452e1ab_0
  - mkl_random=1.0.1=py36h9258bd6_0
  - msys2-conda-epoch=20160418=1
  - nb_anacondacloud=1.4.0=py36_0
  - nb_conda=2.2.0=py36_0
  - nb_conda_kernels=2.1.0=py36_0
  - nbconvert=5.3.1=py36h8dc0fde_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - nbpresent=3.0.2=py36_0
  - notebook=5.4.1=py36_0
  - numpy=1.14.2=py36h5c71026_1
  - numpydoc=0.8.0=py36_0
  - openssl=1.0.2o=h8ea7d77_0
  - packaging=17.1=py36_0
  - pandoc=1.19.2.1=hb2460c7_1
  - pandocfilters=1.4.2=py36h3ef6317_1
  - parso=0.1.1=py36hae3edee_0
  - pickleshare=0.7.4=py36h9de030f_0
  - pip=9.0.3=py36_0
  - prompt_toolkit=1.0.15=py36h60b8f86_0
  - pycparser=2.18=py36hd053e01_1
  - pygments=2.2.0=py36hb010967_0
  - pyopenssl=17.5.0=py36h5b7d817_0
  - pyparsing=2.2.0=py36h785a196_1
  - pyqt=5.9.2=py36h1aa27d4_0
  - pysocks=1.6.8=py36_0
  - python=3.6.5=h0c2934d_0
  - python-dateutil=2.7.2=py36_0
  - pytz=2018.3=py36_0
  - pywinpty=0.5.1=py36_0
  - pyyaml=3.12=py36h1d1928f_1
  - pyzmq=17.0.0=py36hfa6e2cd_0
  - qt=5.9.4=vc14hd9fb3db_0
  - requests=2.18.4=py36h4371aae_1
  - send2trash=1.5.0=py36_0
  - setuptools=39.0.1=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36h4db2310_1
  - snowballstemmer=1.2.1=py36h763602f_0
  - sphinx=1.7.2=py36_0
  - sphinxcontrib=1.0=py36hbbac3d2_1
  - sphinxcontrib-websupport=1.0.1=py36hb5e5916_1
  - sqlite=3.22.0=h9d3ae62_0
  - tbb=2018.0.2=h6538335_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h2698cfe_0
  - tornado=5.0.1=py36_1
  - traitlets=4.3.2=py36h096827d_0
  - typing=3.6.4=py36_0
  - urllib3=1.22=py36h276f60a_0
  - vc=14=h0510ff6_3
  - vs2015_runtime=14.0.25123=3
  - vtk=8.1.0=py36he6bbf13_201
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36h67c50ae_1
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.0=py36_0
  - win_inet_pton=1.0.1=py36he67d7fd_1
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - yaml=0.1.7=hc54c509_2
  - zlib=1.2.11=h8395fce_2
prefix: C:\Users\Paperspace\Miniconda3\envs\py3tensorflow

